name: ci-atomic-openfoam

on:
  push:
    branches: [atomic]
    tags: ['v*.*.*']
  pull_request:
    branches: [atomic]

defaults:
  run:
    shell: bash

jobs:
  build-test-publish:
    name: Image build test and publication
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup VPN
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-workflow

      - name: Setup build
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Collect image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: cr.atmc.dev/atomic-openfoam
          flavor: latest=false
          tags: |
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}},event=tag
            type=semver,pattern=v{{major}}.{{minor}},event=tag
            type=semver,pattern=v{{major}},event=tag
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      - name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          target: atomic-openfoam
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          load: true

      - name: Publish image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: atomic-openfoam
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          push: true
        env:
          DOCKER_BUILD_SUMMARY: false

  release:
    name: Version release
    runs-on: ubuntu-latest
    needs: [build-test-publish]
    if: github.ref_type == 'tag'
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: false
          draft: false
